name: mechanic
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  maps_launcher: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  animate_do: ^3.0.2
  animate_gradient: ^0.0.2
  get: ^4.6.5
  firebase_core: ^2.10.0
  lottie: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^4.5.0
  font_awesome_flutter_named: ^1.1.2+1
  url_launcher: ^6.1.10
  cloud_firestore: ^4.6.0
  carousel_slider: ^4.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

